/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ApiService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "IoRedis": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "PartyCodeTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "PartyTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SocketPartyVpc": {
      "type": "sst.aws.Vpc"
    }
    "UiSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "XstateQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "XstateQueueHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}